CollectorApp.WebUI/Controllers/CategoryManagerController.cs
using CollectorApp.Core.Contracts;
using CollectorApp.Core.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CollectorApp.WebUI.Controllers
{
    public class CategoryManagerController : Controller
    {
		IRepository<Category> context;
		public CategoryManagerController(IRepository<Category> categoriesContext)
		{
			context = categoriesContext;
		}

		public ActionResult Index()
		{
			List<Category> categories = context.Collection().ToList();
			return View(categories);
		}

		public ActionResult Create()
		{
			Category newCategory = new Category();
			return View(newCategory);
		}

		[HttpPost]
		public ActionResult Create(Category category)
		{
			if (!ModelState.IsValid)
			{
				return View(category);
			}
			else
			{
				context.Insert(category);
				context.Commit();
				return RedirectToAction("Index");
			}
		}

		public ActionResult Delete(string Id)
		{
			Category categoryToDelete = context.Find(Id);
			if (categoryToDelete != null)
			{
				return View(categoryToDelete);
			}
			else
			{
				return HttpNotFound();
			}
		}
		[HttpPost]
		[ActionName("Delete")]
		public ActionResult ConfirmDelete(string Id)
		{
			Category categoryToDelete = context.Find(Id);
			if (categoryToDelete != null)
			{
				context.Delete(Id);
				context.Commit();
				return RedirectToAction("Index");
			}
			else
			{
				return HttpNotFound();
			}
		}

		public ActionResult Edit(string Id)
		{
			Category categoryToEdit = context.Find(Id);
			if (categoryToEdit != null)
			{
				return View(categoryToEdit);
			}
			else
			{
				return HttpNotFound();
			}
		}
		[HttpPost]
		public ActionResult Edit(string Id, Category newCategorye)
		{
			Category categoryToEdit = context.Find(Id);
			if (categoryToEdit != null)
			{
				categoryToEdit.CategoryName = newCategorye.CategoryName;
				context.Commit();
				return RedirectToAction("Index");
			}
			else
			{
				return HttpNotFound();
			}
		}

		public ActionResult Details(string Id)
		{
			Category category = context.Find(Id);
			if (category != null) return View(category);
			else return HttpNotFound();
		}
	}
}

CollectorApp.WebUI/Controllers/SubjectManagerController.cs
using CollectorApp.Core.Contracts;
using CollectorApp.Core.Models;
using CollectorApp.Core.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CollectorApp.WebUI.Controllers
{
	public class SubjectManagerController : Controller
	{
		const string PLACEHOLDERIMAGE = "Placeholder.jpg";
		IRepository<Subject> subjectContext;
		IRepository<Category> categoryContext;
		// GET: BookManager
		public SubjectManagerController(IRepository<Subject> subjects, IRepository<Category> categories)
		{
			subjectContext = subjects;
			categoryContext = categories;
		}

		public ActionResult Index()
		{
			List<Subject> subjects = subjectContext.Collection().ToList();
			return View(subjects);
		}

		public ActionResult Create()
		{
			SubjectManagerViewModel viewModel = new SubjectManagerViewModel();
			viewModel.Subject = new Subject();
			viewModel.SubjectCategories = categoryContext.Collection();
			return View(viewModel);
		}

		[HttpPost]
		public ActionResult Create(Subject subject, HttpPostedFileBase image)
		{
			if (!ModelState.IsValid)
			{
				return View(subject);
			}
			else
			{
				if(image != null)
				{
					subject.Image = subject.Id + Path.GetExtension(image.FileName);
					image.SaveAs(Server.MapPath("//Content//SubjectImages//") + subject.Image);
				}
				else
				{
					subject.Image = PLACEHOLDERIMAGE;
				}
				subjectContext.Insert(subject);
				subjectContext.Commit();
				return RedirectToAction("index","Home",new { area = "" });
			}
		}

		public ActionResult Delete(string Id)
		{
			Subject subjectToDelete = subjectContext.Find(Id);
			if (subjectToDelete != null)
			{
				return View(subjectToDelete);
			}
			else
			{
				return HttpNotFound();
			}
		}
		[HttpPost]
		[ActionName("Delete")]
		public ActionResult ConfirmDelete(string Id)
		{
			Subject subjectToDelete = subjectContext.Find(Id);
			if (subjectToDelete != null)
			{
				if(subjectToDelete.Image != PLACEHOLDERIMAGE)
				{
					var imageToDelete = Server.MapPath("//Content//SubjectImages//") + subjectToDelete.Image;
					if (System.IO.File.Exists(imageToDelete))
					{
						System.IO.File.Delete(imageToDelete);
					}
				}
				
				subjectContext.Delete(Id);
				subjectContext.Commit();
				return RedirectToAction("index", "Home", new { area = "" });
			}
			else
			{
				return HttpNotFound();
			}
		}

		public ActionResult Edit(string Id)
		{
			Subject subjectToEdit = subjectContext.Find(Id);
			if (subjectToEdit != null)
			{
				SubjectManagerViewModel viewModel = new SubjectManagerViewModel();
				viewModel.Subject = subjectToEdit;
				viewModel.SubjectCategories = categoryContext.Collection();
				return View(viewModel);
			}
			else
			{
				return HttpNotFound();
			}
		}
		[HttpPost]
		public ActionResult Edit(Subject subject, string Id, HttpPostedFileBase image)
		{
			Subject subjectToEdit = subjectContext.Find(Id);
			if (subjectToEdit != null)
			{
				if (!ModelState.IsValid) return View(subject);
				if(image != null)
				{

					subjectToEdit.Image = subject.Id + Path.GetExtension(image.FileName);
					image.SaveAs(Server.MapPath("//Content//SubjectImages//") + subjectToEdit.Image);
				}

				subjectToEdit.Title = subject.Title;
				subjectToEdit.Description = subject.Description;
				subjectToEdit.Category = subject.Category;
				subjectToEdit.Genre = subject.Genre;
				subjectToEdit.Publisher = subject.Publisher;
				subjectContext.Commit();
				return RedirectToAction("index", "Home", new { area = "" });
			}
			else
			{
				return HttpNotFound();
			}
		}


	}
}

CollectorApp.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Collector", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Main Page", "Index", "Home")</li>
                    <li>@Html.ActionLink("Add collectable", "Create", "SubjectManager")</li>
                    <li>@Html.ActionLink("Add category", "Index", "CategoryManager")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>